export const ROUTE_QUESTIONS = {
  '/classification-of-carb': {
    category: 'Carbohydrates',
    icon: '🧬',
    questions: [
      'What is Carbs?',
      'What are the types of carbohydrates?',
      'Explain monosaccharides with examples',
      'What is the difference between simple and complex carbs?',
      'What are reducing and non-reducing sugars?',
    ],
  },
  '/digestion-of-carb': {
    category: 'Nursing',
    icon: '⚕️',
    questions: [
  "Where does carbohydrate digestion begin?",
  "What enzyme in the mouth begins starch digestion?",
  "Why is chewing important for carbohydrate digestion?",
  "What happens to salivary amylase in the stomach?",
  "Does significant chemical digestion of carbohydrates occur in the stomach?",
  "What is the semi-liquid food mass called that leaves the stomach?",
  "Where does most carbohydrate digestion take place?",
  "Which organ produces pancreatic amylase?",
  "Into which part of the small intestine is pancreatic amylase released?",
  "What does pancreatic amylase break starch into?",
  "What are brush border enzymes?",
  "Where are brush border enzymes located?",
  "What disaccharide does maltase act on?",
  "What are the end products of maltose digestion?",
  "What disaccharide does sucrase act on?",
  "What are the end products of sucrose digestion?",
  "What disaccharide does lactase act on?",
  "What are the end products of lactose digestion?",
  "Name the three monosaccharides produced by carbohydrate digestion.",
  "Which monosaccharide mainly comes from lactose?",
  "Which monosaccharide comes from sucrose and fruits?",
  "How are monosaccharides absorbed into the body?",
  "After absorption, where are monosaccharides transported first?",
  "What is the main monosaccharide used for energy in the body?",
  "What is glycogen?",
  "Which organ stores glucose as glycogen?",
  "What happens to carbohydrate digestion when salivary amylase is inactivated?",
  "Why does carbohydrate digestion pause in the stomach?",
  "What is the role of the small intestine in carbohydrate digestion?",
  "Why are brush border enzymes important?",
  "What is the final step in carbohydrate digestion?",
  "Define the term 'monosaccharide'.",
  "Define the term 'disaccharide'.",
  "Name a dietary source of lactose.",
  "Name a dietary source of fructose.",
  "Name a dietary source of sucrose.",
  "State the exam memory hook for carbohydrate digestion sequence.",
  "Why is small-intestinal digestion considered the 'finishing' phase?",
  "How does carbohydrate digestion support energy metabolism?",
  "What happens to undigested carbohydrates in the large intestine?"
]
,
  },
  '/absorption-of-carb': {
    category: 'Biochemistry',
    icon: '🧪',
    questions: [
  "Where in the gastrointestinal tract are most monosaccharides absorbed?",
  "Which part of the small intestine is the main site for carbohydrate absorption?",
  "What are the three major monosaccharides absorbed by the small intestine?",
  "What transporter takes glucose into enterocytes from the lumen?",
  "What transporter takes galactose into enterocytes from the lumen?",
  "What transporter takes fructose into enterocytes from the lumen?",
  "Is SGLT1 located on the apical or basolateral membrane?",
  "Is GLUT5 located on the apical or basolateral membrane?",
  "Is GLUT2 located on the apical or basolateral membrane?",
  "What is the full name of SGLT1?",
  "What ions are moved along with glucose and galactose by SGLT1?",
  "What type of transport is used by SGLT1?",
  "Which pump maintains the sodium gradient used by SGLT1?",
  "Does SGLT1 require direct ATP usage?",
  "Does GLUT5 require direct ATP usage?",
  "What type of transport does GLUT5 perform?",
  "What type of transport does GLUT2 perform?",
  "Which monosaccharide uses facilitated diffusion to enter enterocytes?",
  "Which monosaccharides use secondary active transport to enter enterocytes?",
  "Which transporter moves glucose, galactose, and fructose out of enterocytes?",
  "Into what blood vessel do absorbed sugars ultimately drain?",
  "After entering the villus capillaries, which vein receives the monosaccharides?",
  "Which organ receives monosaccharides first after absorption?",
  "What happens to fructose in the liver?",
  "What happens to galactose in the liver?",
  "Name one possible fate of glucose in the liver.",
  "What is the term used for glucose storage in the liver?",
  "What is the main energy form transported in blood after carbohydrate digestion?",
  "What symptoms may appear if carbohydrate absorption is impaired?",
  "What condition results from lactase deficiency?",
  "Why does lactose intolerance cause gastrointestinal symptoms?",
  "What condition involves poor absorption of fructose?",
  "Which transporter is involved in fructose malabsorption?",
  "State the sequence of carbohydrate movement from lumen to blood.",
  "What cells line the small intestine and perform nutrient absorption?",
  "What are the small projections on enterocytes that increase surface area?",
  "Why is the jejunum an efficient site for absorption?",
  "What is the exam memory hook for the transporters involved?",
  "Why is secondary active transport helpful for glucose uptake at low concentrations?",
  "Explain the meaning of 'portal circulation' in nutrient transport."
]
,
  },
  '/MetabolicPathwaysOfCarb': {
    category: 'Biochemistry',
    icon: '💊',
    questions: [
  "What are the three major fates of glucose in the body?",
  "Which pathway converts glucose to pyruvate?",
  "Where in the cell does glycolysis occur?",
  "What is the end product of glycolysis under aerobic conditions?",
  "What happens to pyruvate before entering the TCA cycle?",
  "Where does the TCA cycle occur within the cell?",
  "Which molecules generated by the TCA cycle feed into the electron transport chain?",
  "What is the overall energy purpose of glycolysis, TCA cycle, and oxidative phosphorylation?",
  "What is produced when glucose is completely oxidized to CO₂ and H₂O?",
  "What happens to pyruvate under anaerobic conditions?",
  "What is glycogenesis?",
  "What is glycogenolysis?",
  "Which organs are the main sites of glycogen storage?",
  "Which hormone stimulates glycogenesis?",
  "Which hormones stimulate glycogenolysis?",
  "What is the purpose of glycogenolysis in the liver?",
  "What is the purpose of glycogenolysis in muscle during exercise?",
  "What is gluconeogenesis?",
  "Where does gluconeogenesis mainly occur?",
  "What are common precursors for gluconeogenesis?",
  "During what physiological state does gluconeogenesis become important?",
  "Which organs rely heavily on glucose supply during fasting?",
  "What is the pentose phosphate pathway?",
  "Which molecule enters the pentose phosphate pathway?",
  "What are the main products of the pentose phosphate pathway?",
  "What is the role of NADPH in the cell?",
  "What is the role of ribose-5-phosphate?",
  "Does the pentose phosphate pathway primarily produce ATP?",
  "What metabolic pathway converts excess acetyl-CoA into fatty acids?",
  "Why is insulin important for glucose metabolism?",
  "Why is glucagon important for glucose metabolism?",
  "Which metabolic pathway is turned on in the fed state?",
  "Which metabolic pathway is turned on during fasting?",
  "What is meant by 'complete oxidation' of glucose?",
  "What major electron carriers are reduced during glucose oxidation?",
  "How are reduced coenzymes used to produce ATP?",
  "What is the quick memory hook for major carbohydrate pathways?",
  "Why is glucose considered a central metabolic fuel?",
  "Which pathway branches off from glycolysis to make NADPH?",
  "Define the TCA cycle in one sentence."
]
,
  },
  '/DisordersOfCarb': {
    category: 'BioChemistry',
    icon: '📚',
    questions: [
  "What does the term carbohydrate metabolism disorder refer to?",
  "List the three broad functional areas where carbohydrate metabolism can go wrong.",
  "Name two common acquired disorders of carbohydrate metabolism.",
  "Name three inherited disorders of carbohydrate metabolism.",
  "What is the main hormone involved in regulating blood glucose?",
  "What characterises diabetes mellitus in terms of blood glucose levels?",
  "What is the primary defect in type 1 diabetes mellitus?",
  "What is the primary defect in type 2 diabetes mellitus?",
  "Name two long-term complications of uncontrolled diabetes.",
  "Define hypoglycaemia in simple terms.",
  "Name two causes of hypoglycaemia.",
  "Why is the brain especially affected during hypoglycaemia?",
  "List three typical symptoms of hypoglycaemia.",
  "What are glycogen storage diseases (GSD)?",
  "What tissue types are most affected by glycogen storage diseases?",
  "Give an example of a hepatic-type glycogen storage disease.",
  "Give an example of a muscle-type glycogen storage disease.",
  "State two common clinical features of glycogen storage diseases.",
  "Why do many glycogen storage diseases cause fasting hypoglycaemia?",
  "What dietary measure is commonly used in managing glycogen storage diseases?",
  "What enzyme deficiency causes lactose intolerance?",
  "Where in the digestive tract is lactase found?",
  "Why does undigested lactose cause diarrhoea and gas?",
  "Name two dietary approaches to managing lactose intolerance.",
  "What enzyme deficiency is responsible for classical galactosemia?",
  "List two early clinical signs of galactosemia in infants.",
  "Why must infants with galactosemia be taken off milk products?",
  "What major dietary restriction is required in galactosemia?",
  "What enzyme deficiency causes hereditary fructose intolerance?",
  "What sugars must be avoided in hereditary fructose intolerance?",
  "What symptoms may appear after fructose ingestion in hereditary fructose intolerance?",
  "Why can hereditary fructose intolerance lead to hypoglycaemia?",
  "Which two organs are commonly affected in hereditary fructose intolerance?",
  "What is meant by 'enzyme deficiency' in metabolic disorders?",
  "How can abnormal glycogen handling lead to organ enlargement?",
  "State the simple exam grouping of carbohydrate metabolism disorders.",
  "Which conditions fit under 'disorders of blood glucose'?",
  "What is the quick memory hook for disorders of carbohydrate metabolism?",
  "Explain why diabetes mellitus is considered a carbohydrate metabolism disorder.",
  "Explain the link between missing enzymes and specific sugar intolerances."
]
,
  },
  '/RegulationOfBloodGlucose': {
    category: 'BioChemistry',
    icon: '🦴',
    questions: [
  "What is the normal fasting blood glucose range in healthy individuals?",
  "Which hormone lowers blood glucose levels?",
  "Which hormone raises blood glucose levels?",
  "Name two supporting counter-regulatory hormones besides glucagon.",
  "Which organ contains the α and β cells that release glucagon and insulin?",
  "Which tissues respond to insulin by increasing glucose uptake?",
  "Which transporter is moved to the membrane in response to insulin in muscle and adipose tissue?",
  "What metabolic pathways does insulin stimulate in the fed state?",
  "What metabolic pathways does insulin inhibit in the fed state?",
  "How does insulin affect hepatic glucose output?",
  "What hormone is secreted when blood glucose falls during fasting?",
  "What are the main actions of glucagon on the liver?",
  "Which metabolic pathway breaks down glycogen to maintain blood glucose?",
  "Which metabolic pathway produces new glucose during prolonged fasting?",
  "How does adrenaline affect carbohydrate metabolism?",
  "How do cortisol and growth hormone support fasting metabolism?",
  "Which organs are most important for blood glucose regulation?",
  "Why is the brain particularly dependent on stable glucose levels?",
  "What stimulates insulin release from β cells?",
  "What stimulates glucagon release from α cells?",
  "What happens to the insulin:glucagon ratio after a carbohydrate-rich meal?",
  "What happens to the insulin:glucagon ratio during overnight fasting?",
  "Why does hepatic glucose production need to increase during fasting?",
  "What is glycogenesis and when is it dominant?",
  "What is glycogenolysis and when is it dominant?",
  "What is gluconeogenesis and when is it dominant?",
  "How does insulin influence lipid storage?",
  "How does glucagon influence lipid metabolism?",
  "What happens to muscle glucose uptake when insulin levels are high?",
  "Why does hepatic glucose output decrease after meals?",
  "What happens if insulin action is chronically impaired?",
  "What happens if glucagon secretion is inadequate during fasting?",
  "What metabolic fuel can partially replace glucose during prolonged fasting?",
  "Which hormone promotes ketone body production during prolonged fasting?",
  "Define the term post-prandial.",
  "Define the term fasting state.",
  "What is meant by 'counter-regulatory hormones'?",
  "State the basic exam summary for insulin.",
  "State the basic exam summary for glucagon.",
  "What is the memory hook for insulin and glucagon regulation?"
]
,
  },
  '/DiabetesMellitusType1': {
    category: 'BioChemistry',
    icon: '🔬',
    questions: [
  "What is type 1 diabetes mellitus?",
  "What is the primary defect in type 1 diabetes?",
  "Which pancreatic cells are destroyed in type 1 diabetes?",
  "What hormone becomes severely deficient in type 1 diabetes?",
  "Is type 1 diabetes typically autoimmune or non-autoimmune?",
  "In which age groups does type 1 diabetes most commonly present?",
  "Can type 1 diabetes occur in adults?",
  "What is the typical onset pattern of symptoms in type 1 diabetes?",
  "What genetic system is commonly associated with susceptibility to type 1 diabetes?",
  "Name one possible environmental trigger for type 1 diabetes.",
  "What happens to β-cell mass during disease progression?",
  "Why does hyperglycaemia appear late in the disease process?",
  "What metabolic complication results from absolute insulin deficiency?",
  "Why does untreated type 1 diabetes lead to ketone production?",
  "List the three classic symptoms of hyperglycaemia.",
  "Why does weight loss occur despite increased hunger in type 1 diabetes?",
  "Name two non-specific symptoms that may accompany early hyperglycaemia.",
  "What does DKA stand for?",
  "List two common clinical features of diabetic ketoacidosis.",
  "What precipitating factor may trigger DKA in a known diabetic?",
  "Why can type 1 diabetes present as a medical emergency?",
  "Name two acute complications of type 1 diabetes.",
  "Name three chronic microvascular complications of diabetes.",
  "Name two chronic macrovascular complications of diabetes.",
  "Why are type 1 diabetics prone to hypoglycaemia?",
  "What is the lifelong treatment required from diagnosis in type 1 diabetes?",
  "What is meant by a basal–bolus insulin regimen?",
  "What monitoring method helps patients adjust insulin dosing?",
  "Why is dietary counselling important in type 1 diabetes?",
  "Name two components of sick-day rules.",
  "Why is regular physical activity recommended for type 1 patients?",
  "Which organs require periodic screening in type 1 diabetes?",
  "Which eye condition is associated with chronic hyperglycaemia?",
  "Which kidney condition is associated with chronic hyperglycaemia?",
  "Which nerve-related condition is associated with chronic diabetes?",
  "Which cardiovascular outcomes are diabetics at higher risk for?",
  "Why is type 1 diabetes considered a chronic disease?",
  "What is meant by 'absolute insulin deficiency'?",
  "What is the exam summary definition of type 1 diabetes?",
  "What is the quick memory hook for type 1 diabetes?"
]
,
  },
  '/DiabetesMellitusType2': {
    category: 'BioChemistry',
    icon: '🔬',
    questions: [
  "What is type 2 diabetes mellitus?",
  "What is the primary metabolic defect in type 2 diabetes?",
  "Is insulin deficiency in type 2 diabetes absolute or relative in early disease?",
  "What is meant by insulin resistance?",
  "Which tissues commonly show insulin resistance?",
  "Which age group typically develops type 2 diabetes?",
  "Can adolescents develop type 2 diabetes?",
  "What lifestyle factors increase the risk of type 2 diabetes?",
  "What body fat distribution pattern is a major risk factor for type 2 diabetes?",
  "Name two common comorbidities associated with type 2 diabetes.",
  "How does family history influence type 2 diabetes risk?",
  "Which pregnancy-related condition increases later risk of type 2 diabetes?",
  "What happens to β-cells over time in type 2 diabetes?",
  "Why does overt hyperglycaemia appear gradually in type 2 diabetes?",
  "Name three common symptoms of type 2 diabetes.",
  "Why might type 2 diabetes be diagnosed during routine screening?",
  "What types of infections tend to recur in untreated type 2 diabetes?",
  "What is hyperosmolar hyperglycaemic state (HHS)?",
  "Is diabetic ketoacidosis common or uncommon in type 2 diabetes?",
  "Why may unexplained weight loss occur in untreated type 2 diabetes?",
  "Name three microvascular complications of diabetes.",
  "Name three macrovascular complications of diabetes.",
  "Why are foot ulcers a concern in type 2 diabetes?",
  "What is the major long-term goal of managing type 2 diabetes?",
  "What component of management addresses weight and diet?",
  "Why is physical activity beneficial in type 2 diabetes?",
  "What is the first-line oral medication often used in type 2 diabetes?",
  "Why do some patients with type 2 diabetes eventually need insulin?",
  "What laboratory test reflects long-term blood glucose control?",
  "Why should blood pressure and lipids also be monitored in diabetics?",
  "Which organ systems require regular screening in type 2 diabetes?",
  "Why is smoking cessation important in type 2 diabetes management?",
  "What is the difference in insulin status between type 1 and type 2 diabetes?",
  "Why is type 2 diabetes considered a progressive disease?",
  "Name two risk factors related to age and reproduction.",
  "Explain why central obesity promotes insulin resistance.",
  "What is the typical clinical presentation pattern in type 2 diabetes?",
  "What is the exam definition of type 2 diabetes?",
  "What is the quick memory hook for type 2 diabetes?",
  "How does comparing type 1 and type 2 diabetes help in exams?"
]

,
  },
  '/FattyAcidsClassification': {
    category: 'BioChemistry',
    icon: '🔬',
    questions: [
  "What is a fatty acid?",
  "What functional group is present at the terminal end of a fatty acid?",
  "What type of chain makes up the backbone of a fatty acid?",
  "Name two major biological roles of fatty acids.",
  "In what forms do fatty acids mainly exist in the body?",
  "How can fatty acids be classified for exams?",
  "What does chain length refer to in fatty acids?",
  "How many carbon atoms do short-chain fatty acids typically have?",
  "Where are most short-chain fatty acids produced in the body?",
  "Give one example of a short-chain fatty acid.",
  "How many carbons do medium-chain fatty acids usually contain?",
  "Where can medium-chain fatty acids be found in the diet?",
  "Do medium-chain fatty acids absorb faster or slower than long-chain?",
  "How many carbons do long-chain fatty acids typically have?",
  "What is meant by very-long-chain fatty acids?",
  "Name two long-chain fatty acids commonly found in tissues.",
  "What does saturation refer to in fatty acid classification?",
  "What characterises a saturated fatty acid at the molecular level?",
  "Give one dietary example of a saturated fatty acid.",
  "What is the physical state of many saturated fats at room temperature?",
  "What does MUFA stand for?",
  "How many double bonds are present in a monounsaturated fatty acid?",
  "Give one example of a monounsaturated fatty acid.",
  "What does PUFA stand for?",
  "How many double bonds does a polyunsaturated fatty acid contain?",
  "Give two examples of polyunsaturated fatty acids.",
  "Why are PUFAs important for membrane function?",
  "What are trans fatty acids?",
  "How are many trans fatty acids formed industrially?",
  "Why are trans fats discouraged in diet?",
  "What are essential fatty acids?",
  "Name the main essential fatty acids in humans.",
  "What are non-essential fatty acids?",
  "What does the omega classification refer to?",
  "From which end of the fatty acid chain is the omega number counted?",
  "Give an example of an omega-3 fatty acid.",
  "Give an example of an omega-6 fatty acid.",
  "Why are omega-3 and omega-6 fatty acids nutritionally important?",
  "Summarise the exam definition of fatty acids.",
  "What is the quick memory hook for fatty acid classification?"
]

,
  },
  '/MUFA': {
    category: 'BioChemistry',
    icon: '🔬',
    questions: [
  "What does MUFA stand for?",
  "How many double bonds are present in a mono-unsaturated fatty acid?",
  "What type of bond characterises MUFA structure?",
  "What is the most abundant MUFA in the diet?",
  "What is the carbon chain notation for oleic acid?",
  "Are most natural MUFA in cis or trans configuration?",
  "How does cis configuration affect the MUFA chain?",
  "What is the physical state of many MUFA at room temperature?",
  "Name one common MUFA found in human tissues.",
  "What is palmitoleic acid?",
  "What is vaccenic acid?",
  "What type of foods contain vaccenic acid?",
  "Name three dietary oils rich in MUFA.",
  "Name three nuts that are rich in MUFA.",
  "Is avocado considered a MUFA-rich food?",
  "Do MUFA occur only in plant foods?",
  "How do MUFA affect membrane fluidity?",
  "What dietary pattern is known for being rich in MUFA?",
  "What effect may MUFA have on LDL-cholesterol when replacing saturated fats?",
  "How might MUFA intake affect insulin sensitivity?",
  "How may MUFA influence blood pressure in some studies?",
  "Why is substitution important when considering MUFA health effects?",
  "Do MUFA provide fewer calories than other fats?",
  "Why is portion control still important with MUFA?",
  "Do MUFA automatically make a diet healthy?",
  "What other food groups support a heart-healthy MUFA-rich diet?",
  "Why are MUFA compared with saturated fats in exams?",
  "Why are MUFA compared with trans fats in clinical nutrition?",
  "What is a key exam example of a MUFA-rich oil?",
  "What is the major fatty acid in olive oil?",
  "How do MUFA differ structurally from PUFA?",
  "How do MUFA differ structurally from saturated fatty acids?",
  "In metabolic syndrome, what dietary fat shift is often recommended?",
  "How do MUFA relate to cardiovascular risk?",
  "What is one clinical condition where MUFA-rich diets may help glycaemic control?",
  "What does the phrase 'relative to saturated fat' imply in MUFA research findings?",
  "What is the exam summary definition of MUFA?",
  "List two key clinical benefits associated with MUFA intake.",
  "What is the quick memory hook for MUFA?",
  "How can MUFA intake be incorporated without excess calories?"
]

,
  },
  '/PUFA': {
    category: 'BioChemistry',
    icon: '🔬',
    questions: [
  "What does PUFA stand for?",
  "How many double bonds must a fatty acid have to be considered a PUFA?",
  "What is the key structural feature of PUFA?",
  "Name the two main families of PUFA.",
  "Which PUFA are considered essential for humans?",
  "What does the omega (ω) number indicate in PUFA classification?",
  "Where is the first double bond located in omega-6 PUFA?",
  "Where is the first double bond located in omega-3 PUFA?",
  "Give an example of an omega-6 PUFA.",
  "Give an example of another omega-6 PUFA found in tissues.",
  "Give an example of an omega-3 PUFA found in plants.",
  "Give an example of two long-chain omega-3 PUFA found in fish.",
  "Which essential omega-3 fatty acid is a precursor to EPA and DHA?",
  "Is conversion of ALA to EPA and DHA efficient in humans?",
  "Name three vegetable oils rich in omega-6 PUFA.",
  "Name three nuts or seeds rich in omega-6 PUFA.",
  "Name four oily fish rich in EPA and DHA.",
  "Name three plant-based sources of ALA.",
  "What dietary supplements provide omega-3 PUFA?",
  "How do PUFA affect membrane fluidity?",
  "Which PUFA family contributes to eicosanoid synthesis?",
  "What are eicosanoids derived from PUFA involved in?",
  "How can replacing saturated fat with PUFA affect LDL-cholesterol?",
  "Which omega-3 PUFA may help reduce triglyceride levels?",
  "Which omega-3 PUFA is a major structural component in the brain and retina?",
  "Which organ's development benefits from DHA?",
  "How might long-chain omega-3 PUFA affect blood pressure?",
  "What anti-inflammatory role is associated with omega-3 PUFA?",
  "How does a high omega-6 to omega-3 ratio potentially affect inflammation?",
  "Which PUFA family provides precursors for both pro- and anti-inflammatory mediators?",
  "Which common dietary pattern is often high in omega-6 and low in omega-3?",
  "What dietary change is often recommended to improve omega-6/omega-3 balance?",
  "Why are PUFA important for cardiovascular health?",
  "Why are omega-3 PUFA important for neurological health?",
  "Which two essential PUFA must be obtained from the diet?",
  "Which food groups provide most omega-6 PUFA?",
  "Which food groups provide most omega-3 PUFA?",
  "What is the exam definition of PUFA?",
  "List four key clinical benefits associated with PUFA intake.",
  "What is the quick memory hook for PUFA?"
]

,
  },
  '/EssentialFattyAcids': {
    category: 'BioChemistry',
    icon: '🔬',
    questions: [
  "What are essential fatty acids?",
  "Why are some fatty acids considered essential for humans?",
  "Which enzymes are lacking in humans that make certain PUFA essential?",
  "Name the two strictly essential fatty acids for humans.",
  "What does LA stand for?",
  "What does ALA stand for?",
  "Which omega family does linoleic acid belong to?",
  "Which omega family does alpha-linolenic acid belong to?",
  "What long-chain PUFA is derived from linoleic acid?",
  "What long-chain PUFA are derived from alpha-linolenic acid?",
  "Is conversion of ALA to EPA and DHA efficient in humans?",
  "Name three dietary sources rich in linoleic acid.",
  "Name three dietary sources rich in alpha-linolenic acid.",
  "What does 'conditionally essential' mean in relation to fatty acids?",
  "Name a fatty acid that may become conditionally essential.",
  "In what situations might EPA or DHA become conditionally essential?",
  "What structural role do essential fatty acids play in cells?",
  "Why are essential fatty acids important for the brain and retina?",
  "What are eicosanoids derived from?",
  "Name two classes of lipid mediators formed from AA or EPA.",
  "What physiological processes are influenced by eicosanoids?",
  "How do omega-6 and omega-3 derived mediators differ in inflammatory effects?",
  "What skin-related symptom suggests EFA deficiency?",
  "How can EFA deficiency affect growth in children?",
  "Why may wound healing be impaired in EFA deficiency?",
  "Name two clinical situations where EFA deficiency may occur.",
  "Why must parenteral nutrition formulas contain essential fatty acids?",
  "How can extremely low-fat diets lead to deficiency?",
  "What cardiovascular benefit is associated with adequate omega-3 intake?",
  "What neural or cognitive benefit is associated with DHA intake?",
  "What is thrombocytopenia and how does it relate to severe EFA deficiency?",
  "Which fatty acid is a major structural component in neural membranes?",
  "Which plant-based foods are good sources of ALA?",
  "Which oils provide significant amounts of LA?",
  "Summarise the key physiological roles of essential fatty acids.",
  "What is the exam definition of essential fatty acids?",
  "What are the main symptoms of essential fatty acid deficiency?",
  "Which essential fatty acid belongs to the omega-6 family?",
  "Which essential fatty acid belongs to the omega-3 family?",
  "What is the quick memory hook for essential fatty acids?"
]

,
  },
  '/DiabetesMellitusType1': {
    category: 'BioChemistry',
    icon: '🔬',
    questions: [
  "What is type 1 diabetes mellitus?",
  "What is the primary defect in type 1 diabetes?",
  "Which pancreatic cells are destroyed in type 1 diabetes?",
  "What hormone becomes severely deficient in type 1 diabetes?",
  "Is type 1 diabetes typically autoimmune or non-autoimmune?",
  "In which age groups does type 1 diabetes most commonly present?",
  "Can type 1 diabetes occur in adults?",
  "What is the typical onset pattern of symptoms in type 1 diabetes?",
  "What genetic system is commonly associated with susceptibility to type 1 diabetes?",
  "Name one possible environmental trigger for type 1 diabetes.",
  "What happens to β-cell mass during disease progression?",
  "Why does hyperglycaemia appear late in the disease process?",
  "What metabolic complication results from absolute insulin deficiency?",
  "Why does untreated type 1 diabetes lead to ketone production?",
  "List the three classic symptoms of hyperglycaemia.",
  "Why does weight loss occur despite increased hunger in type 1 diabetes?",
  "Name two non-specific symptoms that may accompany early hyperglycaemia.",
  "What does DKA stand for?",
  "List two common clinical features of diabetic ketoacidosis.",
  "What precipitating factor may trigger DKA in a known diabetic?",
  "Why can type 1 diabetes present as a medical emergency?",
  "Name two acute complications of type 1 diabetes.",
  "Name three chronic microvascular complications of diabetes.",
  "Name two chronic macrovascular complications of diabetes.",
  "Why are type 1 diabetics prone to hypoglycaemia?",
  "What is the lifelong treatment required from diagnosis in type 1 diabetes?",
  "What is meant by a basal–bolus insulin regimen?",
  "What monitoring method helps patients adjust insulin dosing?",
  "Why is dietary counselling important in type 1 diabetes?",
  "Name two components of sick-day rules.",
  "Why is regular physical activity recommended for type 1 patients?",
  "Which organs require periodic screening in type 1 diabetes?",
  "Which eye condition is associated with chronic hyperglycaemia?",
  "Which kidney condition is associated with chronic hyperglycaemia?",
  "Which nerve-related condition is associated with chronic diabetes?",
  "Which cardiovascular outcomes are diabetics at higher risk for?",
  "Why is type 1 diabetes considered a chronic disease?",
  "What is meant by 'absolute insulin deficiency'?",
  "What is the exam summary definition of type 1 diabetes?",
  "What is the quick memory hook for type 1 diabetes?"
]
,
  },
  '/DiabetesMellitusType1': {
    category: 'BioChemistry',
    icon: '🔬',
    questions: [
  "What is type 1 diabetes mellitus?",
  "What is the primary defect in type 1 diabetes?",
  "Which pancreatic cells are destroyed in type 1 diabetes?",
  "What hormone becomes severely deficient in type 1 diabetes?",
  "Is type 1 diabetes typically autoimmune or non-autoimmune?",
  "In which age groups does type 1 diabetes most commonly present?",
  "Can type 1 diabetes occur in adults?",
  "What is the typical onset pattern of symptoms in type 1 diabetes?",
  "What genetic system is commonly associated with susceptibility to type 1 diabetes?",
  "Name one possible environmental trigger for type 1 diabetes.",
  "What happens to β-cell mass during disease progression?",
  "Why does hyperglycaemia appear late in the disease process?",
  "What metabolic complication results from absolute insulin deficiency?",
  "Why does untreated type 1 diabetes lead to ketone production?",
  "List the three classic symptoms of hyperglycaemia.",
  "Why does weight loss occur despite increased hunger in type 1 diabetes?",
  "Name two non-specific symptoms that may accompany early hyperglycaemia.",
  "What does DKA stand for?",
  "List two common clinical features of diabetic ketoacidosis.",
  "What precipitating factor may trigger DKA in a known diabetic?",
  "Why can type 1 diabetes present as a medical emergency?",
  "Name two acute complications of type 1 diabetes.",
  "Name three chronic microvascular complications of diabetes.",
  "Name two chronic macrovascular complications of diabetes.",
  "Why are type 1 diabetics prone to hypoglycaemia?",
  "What is the lifelong treatment required from diagnosis in type 1 diabetes?",
  "What is meant by a basal–bolus insulin regimen?",
  "What monitoring method helps patients adjust insulin dosing?",
  "Why is dietary counselling important in type 1 diabetes?",
  "Name two components of sick-day rules.",
  "Why is regular physical activity recommended for type 1 patients?",
  "Which organs require periodic screening in type 1 diabetes?",
  "Which eye condition is associated with chronic hyperglycaemia?",
  "Which kidney condition is associated with chronic hyperglycaemia?",
  "Which nerve-related condition is associated with chronic diabetes?",
  "Which cardiovascular outcomes are diabetics at higher risk for?",
  "Why is type 1 diabetes considered a chronic disease?",
  "What is meant by 'absolute insulin deficiency'?",
  "What is the exam summary definition of type 1 diabetes?",
  "What is the quick memory hook for type 1 diabetes?"
]
,
  },
  '/DiabetesMellitusType1': {
    category: 'BioChemistry',
    icon: '🔬',
    questions: [
  "What is type 1 diabetes mellitus?",
  "What is the primary defect in type 1 diabetes?",
  "Which pancreatic cells are destroyed in type 1 diabetes?",
  "What hormone becomes severely deficient in type 1 diabetes?",
  "Is type 1 diabetes typically autoimmune or non-autoimmune?",
  "In which age groups does type 1 diabetes most commonly present?",
  "Can type 1 diabetes occur in adults?",
  "What is the typical onset pattern of symptoms in type 1 diabetes?",
  "What genetic system is commonly associated with susceptibility to type 1 diabetes?",
  "Name one possible environmental trigger for type 1 diabetes.",
  "What happens to β-cell mass during disease progression?",
  "Why does hyperglycaemia appear late in the disease process?",
  "What metabolic complication results from absolute insulin deficiency?",
  "Why does untreated type 1 diabetes lead to ketone production?",
  "List the three classic symptoms of hyperglycaemia.",
  "Why does weight loss occur despite increased hunger in type 1 diabetes?",
  "Name two non-specific symptoms that may accompany early hyperglycaemia.",
  "What does DKA stand for?",
  "List two common clinical features of diabetic ketoacidosis.",
  "What precipitating factor may trigger DKA in a known diabetic?",
  "Why can type 1 diabetes present as a medical emergency?",
  "Name two acute complications of type 1 diabetes.",
  "Name three chronic microvascular complications of diabetes.",
  "Name two chronic macrovascular complications of diabetes.",
  "Why are type 1 diabetics prone to hypoglycaemia?",
  "What is the lifelong treatment required from diagnosis in type 1 diabetes?",
  "What is meant by a basal–bolus insulin regimen?",
  "What monitoring method helps patients adjust insulin dosing?",
  "Why is dietary counselling important in type 1 diabetes?",
  "Name two components of sick-day rules.",
  "Why is regular physical activity recommended for type 1 patients?",
  "Which organs require periodic screening in type 1 diabetes?",
  "Which eye condition is associated with chronic hyperglycaemia?",
  "Which kidney condition is associated with chronic hyperglycaemia?",
  "Which nerve-related condition is associated with chronic diabetes?",
  "Which cardiovascular outcomes are diabetics at higher risk for?",
  "Why is type 1 diabetes considered a chronic disease?",
  "What is meant by 'absolute insulin deficiency'?",
  "What is the exam summary definition of type 1 diabetes?",
  "What is the quick memory hook for type 1 diabetes?"
]
,
  },
  '/DiabetesMellitusType1': {
    category: 'BioChemistry',
    icon: '🔬',
    questions: [
  "What is type 1 diabetes mellitus?",
  "What is the primary defect in type 1 diabetes?",
  "Which pancreatic cells are destroyed in type 1 diabetes?",
  "What hormone becomes severely deficient in type 1 diabetes?",
  "Is type 1 diabetes typically autoimmune or non-autoimmune?",
  "In which age groups does type 1 diabetes most commonly present?",
  "Can type 1 diabetes occur in adults?",
  "What is the typical onset pattern of symptoms in type 1 diabetes?",
  "What genetic system is commonly associated with susceptibility to type 1 diabetes?",
  "Name one possible environmental trigger for type 1 diabetes.",
  "What happens to β-cell mass during disease progression?",
  "Why does hyperglycaemia appear late in the disease process?",
  "What metabolic complication results from absolute insulin deficiency?",
  "Why does untreated type 1 diabetes lead to ketone production?",
  "List the three classic symptoms of hyperglycaemia.",
  "Why does weight loss occur despite increased hunger in type 1 diabetes?",
  "Name two non-specific symptoms that may accompany early hyperglycaemia.",
  "What does DKA stand for?",
  "List two common clinical features of diabetic ketoacidosis.",
  "What precipitating factor may trigger DKA in a known diabetic?",
  "Why can type 1 diabetes present as a medical emergency?",
  "Name two acute complications of type 1 diabetes.",
  "Name three chronic microvascular complications of diabetes.",
  "Name two chronic macrovascular complications of diabetes.",
  "Why are type 1 diabetics prone to hypoglycaemia?",
  "What is the lifelong treatment required from diagnosis in type 1 diabetes?",
  "What is meant by a basal–bolus insulin regimen?",
  "What monitoring method helps patients adjust insulin dosing?",
  "Why is dietary counselling important in type 1 diabetes?",
  "Name two components of sick-day rules.",
  "Why is regular physical activity recommended for type 1 patients?",
  "Which organs require periodic screening in type 1 diabetes?",
  "Which eye condition is associated with chronic hyperglycaemia?",
  "Which kidney condition is associated with chronic hyperglycaemia?",
  "Which nerve-related condition is associated with chronic diabetes?",
  "Which cardiovascular outcomes are diabetics at higher risk for?",
  "Why is type 1 diabetes considered a chronic disease?",
  "What is meant by 'absolute insulin deficiency'?",
  "What is the exam summary definition of type 1 diabetes?",
  "What is the quick memory hook for type 1 diabetes?"
]
,
  },
  '/DiabetesMellitusType1': {
    category: 'BioChemistry',
    icon: '🔬',
    questions: [
  "What is type 1 diabetes mellitus?",
  "What is the primary defect in type 1 diabetes?",
  "Which pancreatic cells are destroyed in type 1 diabetes?",
  "What hormone becomes severely deficient in type 1 diabetes?",
  "Is type 1 diabetes typically autoimmune or non-autoimmune?",
  "In which age groups does type 1 diabetes most commonly present?",
  "Can type 1 diabetes occur in adults?",
  "What is the typical onset pattern of symptoms in type 1 diabetes?",
  "What genetic system is commonly associated with susceptibility to type 1 diabetes?",
  "Name one possible environmental trigger for type 1 diabetes.",
  "What happens to β-cell mass during disease progression?",
  "Why does hyperglycaemia appear late in the disease process?",
  "What metabolic complication results from absolute insulin deficiency?",
  "Why does untreated type 1 diabetes lead to ketone production?",
  "List the three classic symptoms of hyperglycaemia.",
  "Why does weight loss occur despite increased hunger in type 1 diabetes?",
  "Name two non-specific symptoms that may accompany early hyperglycaemia.",
  "What does DKA stand for?",
  "List two common clinical features of diabetic ketoacidosis.",
  "What precipitating factor may trigger DKA in a known diabetic?",
  "Why can type 1 diabetes present as a medical emergency?",
  "Name two acute complications of type 1 diabetes.",
  "Name three chronic microvascular complications of diabetes.",
  "Name two chronic macrovascular complications of diabetes.",
  "Why are type 1 diabetics prone to hypoglycaemia?",
  "What is the lifelong treatment required from diagnosis in type 1 diabetes?",
  "What is meant by a basal–bolus insulin regimen?",
  "What monitoring method helps patients adjust insulin dosing?",
  "Why is dietary counselling important in type 1 diabetes?",
  "Name two components of sick-day rules.",
  "Why is regular physical activity recommended for type 1 patients?",
  "Which organs require periodic screening in type 1 diabetes?",
  "Which eye condition is associated with chronic hyperglycaemia?",
  "Which kidney condition is associated with chronic hyperglycaemia?",
  "Which nerve-related condition is associated with chronic diabetes?",
  "Which cardiovascular outcomes are diabetics at higher risk for?",
  "Why is type 1 diabetes considered a chronic disease?",
  "What is meant by 'absolute insulin deficiency'?",
  "What is the exam summary definition of type 1 diabetes?",
  "What is the quick memory hook for type 1 diabetes?"
]
,
  },
  '/DiabetesMellitusType1': {
    category: 'BioChemistry',
    icon: '🔬',
    questions: [
  "What is type 1 diabetes mellitus?",
  "What is the primary defect in type 1 diabetes?",
  "Which pancreatic cells are destroyed in type 1 diabetes?",
  "What hormone becomes severely deficient in type 1 diabetes?",
  "Is type 1 diabetes typically autoimmune or non-autoimmune?",
  "In which age groups does type 1 diabetes most commonly present?",
  "Can type 1 diabetes occur in adults?",
  "What is the typical onset pattern of symptoms in type 1 diabetes?",
  "What genetic system is commonly associated with susceptibility to type 1 diabetes?",
  "Name one possible environmental trigger for type 1 diabetes.",
  "What happens to β-cell mass during disease progression?",
  "Why does hyperglycaemia appear late in the disease process?",
  "What metabolic complication results from absolute insulin deficiency?",
  "Why does untreated type 1 diabetes lead to ketone production?",
  "List the three classic symptoms of hyperglycaemia.",
  "Why does weight loss occur despite increased hunger in type 1 diabetes?",
  "Name two non-specific symptoms that may accompany early hyperglycaemia.",
  "What does DKA stand for?",
  "List two common clinical features of diabetic ketoacidosis.",
  "What precipitating factor may trigger DKA in a known diabetic?",
  "Why can type 1 diabetes present as a medical emergency?",
  "Name two acute complications of type 1 diabetes.",
  "Name three chronic microvascular complications of diabetes.",
  "Name two chronic macrovascular complications of diabetes.",
  "Why are type 1 diabetics prone to hypoglycaemia?",
  "What is the lifelong treatment required from diagnosis in type 1 diabetes?",
  "What is meant by a basal–bolus insulin regimen?",
  "What monitoring method helps patients adjust insulin dosing?",
  "Why is dietary counselling important in type 1 diabetes?",
  "Name two components of sick-day rules.",
  "Why is regular physical activity recommended for type 1 patients?",
  "Which organs require periodic screening in type 1 diabetes?",
  "Which eye condition is associated with chronic hyperglycaemia?",
  "Which kidney condition is associated with chronic hyperglycaemia?",
  "Which nerve-related condition is associated with chronic diabetes?",
  "Which cardiovascular outcomes are diabetics at higher risk for?",
  "Why is type 1 diabetes considered a chronic disease?",
  "What is meant by 'absolute insulin deficiency'?",
  "What is the exam summary definition of type 1 diabetes?",
  "What is the quick memory hook for type 1 diabetes?"
]
,
  },
  '/DiabetesMellitusType1': {
    category: 'BioChemistry',
    icon: '🔬',
    questions: [
  "What is type 1 diabetes mellitus?",
  "What is the primary defect in type 1 diabetes?",
  "Which pancreatic cells are destroyed in type 1 diabetes?",
  "What hormone becomes severely deficient in type 1 diabetes?",
  "Is type 1 diabetes typically autoimmune or non-autoimmune?",
  "In which age groups does type 1 diabetes most commonly present?",
  "Can type 1 diabetes occur in adults?",
  "What is the typical onset pattern of symptoms in type 1 diabetes?",
  "What genetic system is commonly associated with susceptibility to type 1 diabetes?",
  "Name one possible environmental trigger for type 1 diabetes.",
  "What happens to β-cell mass during disease progression?",
  "Why does hyperglycaemia appear late in the disease process?",
  "What metabolic complication results from absolute insulin deficiency?",
  "Why does untreated type 1 diabetes lead to ketone production?",
  "List the three classic symptoms of hyperglycaemia.",
  "Why does weight loss occur despite increased hunger in type 1 diabetes?",
  "Name two non-specific symptoms that may accompany early hyperglycaemia.",
  "What does DKA stand for?",
  "List two common clinical features of diabetic ketoacidosis.",
  "What precipitating factor may trigger DKA in a known diabetic?",
  "Why can type 1 diabetes present as a medical emergency?",
  "Name two acute complications of type 1 diabetes.",
  "Name three chronic microvascular complications of diabetes.",
  "Name two chronic macrovascular complications of diabetes.",
  "Why are type 1 diabetics prone to hypoglycaemia?",
  "What is the lifelong treatment required from diagnosis in type 1 diabetes?",
  "What is meant by a basal–bolus insulin regimen?",
  "What monitoring method helps patients adjust insulin dosing?",
  "Why is dietary counselling important in type 1 diabetes?",
  "Name two components of sick-day rules.",
  "Why is regular physical activity recommended for type 1 patients?",
  "Which organs require periodic screening in type 1 diabetes?",
  "Which eye condition is associated with chronic hyperglycaemia?",
  "Which kidney condition is associated with chronic hyperglycaemia?",
  "Which nerve-related condition is associated with chronic diabetes?",
  "Which cardiovascular outcomes are diabetics at higher risk for?",
  "Why is type 1 diabetes considered a chronic disease?",
  "What is meant by 'absolute insulin deficiency'?",
  "What is the exam summary definition of type 1 diabetes?",
  "What is the quick memory hook for type 1 diabetes?"
]
,
  },
  '/DiabetesMellitusType1': {
    category: 'BioChemistry',
    icon: '🔬',
    questions: [
  "What is type 1 diabetes mellitus?",
  "What is the primary defect in type 1 diabetes?",
  "Which pancreatic cells are destroyed in type 1 diabetes?",
  "What hormone becomes severely deficient in type 1 diabetes?",
  "Is type 1 diabetes typically autoimmune or non-autoimmune?",
  "In which age groups does type 1 diabetes most commonly present?",
  "Can type 1 diabetes occur in adults?",
  "What is the typical onset pattern of symptoms in type 1 diabetes?",
  "What genetic system is commonly associated with susceptibility to type 1 diabetes?",
  "Name one possible environmental trigger for type 1 diabetes.",
  "What happens to β-cell mass during disease progression?",
  "Why does hyperglycaemia appear late in the disease process?",
  "What metabolic complication results from absolute insulin deficiency?",
  "Why does untreated type 1 diabetes lead to ketone production?",
  "List the three classic symptoms of hyperglycaemia.",
  "Why does weight loss occur despite increased hunger in type 1 diabetes?",
  "Name two non-specific symptoms that may accompany early hyperglycaemia.",
  "What does DKA stand for?",
  "List two common clinical features of diabetic ketoacidosis.",
  "What precipitating factor may trigger DKA in a known diabetic?",
  "Why can type 1 diabetes present as a medical emergency?",
  "Name two acute complications of type 1 diabetes.",
  "Name three chronic microvascular complications of diabetes.",
  "Name two chronic macrovascular complications of diabetes.",
  "Why are type 1 diabetics prone to hypoglycaemia?",
  "What is the lifelong treatment required from diagnosis in type 1 diabetes?",
  "What is meant by a basal–bolus insulin regimen?",
  "What monitoring method helps patients adjust insulin dosing?",
  "Why is dietary counselling important in type 1 diabetes?",
  "Name two components of sick-day rules.",
  "Why is regular physical activity recommended for type 1 patients?",
  "Which organs require periodic screening in type 1 diabetes?",
  "Which eye condition is associated with chronic hyperglycaemia?",
  "Which kidney condition is associated with chronic hyperglycaemia?",
  "Which nerve-related condition is associated with chronic diabetes?",
  "Which cardiovascular outcomes are diabetics at higher risk for?",
  "Why is type 1 diabetes considered a chronic disease?",
  "What is meant by 'absolute insulin deficiency'?",
  "What is the exam summary definition of type 1 diabetes?",
  "What is the quick memory hook for type 1 diabetes?"
]
,
  },
  '/DiabetesMellitusType1': {
    category: 'BioChemistry',
    icon: '🔬',
    questions: [
  "What is type 1 diabetes mellitus?",
  "What is the primary defect in type 1 diabetes?",
  "Which pancreatic cells are destroyed in type 1 diabetes?",
  "What hormone becomes severely deficient in type 1 diabetes?",
  "Is type 1 diabetes typically autoimmune or non-autoimmune?",
  "In which age groups does type 1 diabetes most commonly present?",
  "Can type 1 diabetes occur in adults?",
  "What is the typical onset pattern of symptoms in type 1 diabetes?",
  "What genetic system is commonly associated with susceptibility to type 1 diabetes?",
  "Name one possible environmental trigger for type 1 diabetes.",
  "What happens to β-cell mass during disease progression?",
  "Why does hyperglycaemia appear late in the disease process?",
  "What metabolic complication results from absolute insulin deficiency?",
  "Why does untreated type 1 diabetes lead to ketone production?",
  "List the three classic symptoms of hyperglycaemia.",
  "Why does weight loss occur despite increased hunger in type 1 diabetes?",
  "Name two non-specific symptoms that may accompany early hyperglycaemia.",
  "What does DKA stand for?",
  "List two common clinical features of diabetic ketoacidosis.",
  "What precipitating factor may trigger DKA in a known diabetic?",
  "Why can type 1 diabetes present as a medical emergency?",
  "Name two acute complications of type 1 diabetes.",
  "Name three chronic microvascular complications of diabetes.",
  "Name two chronic macrovascular complications of diabetes.",
  "Why are type 1 diabetics prone to hypoglycaemia?",
  "What is the lifelong treatment required from diagnosis in type 1 diabetes?",
  "What is meant by a basal–bolus insulin regimen?",
  "What monitoring method helps patients adjust insulin dosing?",
  "Why is dietary counselling important in type 1 diabetes?",
  "Name two components of sick-day rules.",
  "Why is regular physical activity recommended for type 1 patients?",
  "Which organs require periodic screening in type 1 diabetes?",
  "Which eye condition is associated with chronic hyperglycaemia?",
  "Which kidney condition is associated with chronic hyperglycaemia?",
  "Which nerve-related condition is associated with chronic diabetes?",
  "Which cardiovascular outcomes are diabetics at higher risk for?",
  "Why is type 1 diabetes considered a chronic disease?",
  "What is meant by 'absolute insulin deficiency'?",
  "What is the exam summary definition of type 1 diabetes?",
  "What is the quick memory hook for type 1 diabetes?"
]
,
  },
  '/DiabetesMellitusType1': {
    category: 'BioChemistry',
    icon: '🔬',
    questions: [
  "What is type 1 diabetes mellitus?",
  "What is the primary defect in type 1 diabetes?",
  "Which pancreatic cells are destroyed in type 1 diabetes?",
  "What hormone becomes severely deficient in type 1 diabetes?",
  "Is type 1 diabetes typically autoimmune or non-autoimmune?",
  "In which age groups does type 1 diabetes most commonly present?",
  "Can type 1 diabetes occur in adults?",
  "What is the typical onset pattern of symptoms in type 1 diabetes?",
  "What genetic system is commonly associated with susceptibility to type 1 diabetes?",
  "Name one possible environmental trigger for type 1 diabetes.",
  "What happens to β-cell mass during disease progression?",
  "Why does hyperglycaemia appear late in the disease process?",
  "What metabolic complication results from absolute insulin deficiency?",
  "Why does untreated type 1 diabetes lead to ketone production?",
  "List the three classic symptoms of hyperglycaemia.",
  "Why does weight loss occur despite increased hunger in type 1 diabetes?",
  "Name two non-specific symptoms that may accompany early hyperglycaemia.",
  "What does DKA stand for?",
  "List two common clinical features of diabetic ketoacidosis.",
  "What precipitating factor may trigger DKA in a known diabetic?",
  "Why can type 1 diabetes present as a medical emergency?",
  "Name two acute complications of type 1 diabetes.",
  "Name three chronic microvascular complications of diabetes.",
  "Name two chronic macrovascular complications of diabetes.",
  "Why are type 1 diabetics prone to hypoglycaemia?",
  "What is the lifelong treatment required from diagnosis in type 1 diabetes?",
  "What is meant by a basal–bolus insulin regimen?",
  "What monitoring method helps patients adjust insulin dosing?",
  "Why is dietary counselling important in type 1 diabetes?",
  "Name two components of sick-day rules.",
  "Why is regular physical activity recommended for type 1 patients?",
  "Which organs require periodic screening in type 1 diabetes?",
  "Which eye condition is associated with chronic hyperglycaemia?",
  "Which kidney condition is associated with chronic hyperglycaemia?",
  "Which nerve-related condition is associated with chronic diabetes?",
  "Which cardiovascular outcomes are diabetics at higher risk for?",
  "Why is type 1 diabetes considered a chronic disease?",
  "What is meant by 'absolute insulin deficiency'?",
  "What is the exam summary definition of type 1 diabetes?",
  "What is the quick memory hook for type 1 diabetes?"
]
,
  },
  '/DiabetesMellitusType1': {
    category: 'BioChemistry',
    icon: '🔬',
    questions: [
  "What is type 1 diabetes mellitus?",
  "What is the primary defect in type 1 diabetes?",
  "Which pancreatic cells are destroyed in type 1 diabetes?",
  "What hormone becomes severely deficient in type 1 diabetes?",
  "Is type 1 diabetes typically autoimmune or non-autoimmune?",
  "In which age groups does type 1 diabetes most commonly present?",
  "Can type 1 diabetes occur in adults?",
  "What is the typical onset pattern of symptoms in type 1 diabetes?",
  "What genetic system is commonly associated with susceptibility to type 1 diabetes?",
  "Name one possible environmental trigger for type 1 diabetes.",
  "What happens to β-cell mass during disease progression?",
  "Why does hyperglycaemia appear late in the disease process?",
  "What metabolic complication results from absolute insulin deficiency?",
  "Why does untreated type 1 diabetes lead to ketone production?",
  "List the three classic symptoms of hyperglycaemia.",
  "Why does weight loss occur despite increased hunger in type 1 diabetes?",
  "Name two non-specific symptoms that may accompany early hyperglycaemia.",
  "What does DKA stand for?",
  "List two common clinical features of diabetic ketoacidosis.",
  "What precipitating factor may trigger DKA in a known diabetic?",
  "Why can type 1 diabetes present as a medical emergency?",
  "Name two acute complications of type 1 diabetes.",
  "Name three chronic microvascular complications of diabetes.",
  "Name two chronic macrovascular complications of diabetes.",
  "Why are type 1 diabetics prone to hypoglycaemia?",
  "What is the lifelong treatment required from diagnosis in type 1 diabetes?",
  "What is meant by a basal–bolus insulin regimen?",
  "What monitoring method helps patients adjust insulin dosing?",
  "Why is dietary counselling important in type 1 diabetes?",
  "Name two components of sick-day rules.",
  "Why is regular physical activity recommended for type 1 patients?",
  "Which organs require periodic screening in type 1 diabetes?",
  "Which eye condition is associated with chronic hyperglycaemia?",
  "Which kidney condition is associated with chronic hyperglycaemia?",
  "Which nerve-related condition is associated with chronic diabetes?",
  "Which cardiovascular outcomes are diabetics at higher risk for?",
  "Why is type 1 diabetes considered a chronic disease?",
  "What is meant by 'absolute insulin deficiency'?",
  "What is the exam summary definition of type 1 diabetes?",
  "What is the quick memory hook for type 1 diabetes?"
]
,
  },
  '/DiabetesMellitusType1': {
    category: 'BioChemistry',
    icon: '🔬',
    questions: [
  "What is type 1 diabetes mellitus?",
  "What is the primary defect in type 1 diabetes?",
  "Which pancreatic cells are destroyed in type 1 diabetes?",
  "What hormone becomes severely deficient in type 1 diabetes?",
  "Is type 1 diabetes typically autoimmune or non-autoimmune?",
  "In which age groups does type 1 diabetes most commonly present?",
  "Can type 1 diabetes occur in adults?",
  "What is the typical onset pattern of symptoms in type 1 diabetes?",
  "What genetic system is commonly associated with susceptibility to type 1 diabetes?",
  "Name one possible environmental trigger for type 1 diabetes.",
  "What happens to β-cell mass during disease progression?",
  "Why does hyperglycaemia appear late in the disease process?",
  "What metabolic complication results from absolute insulin deficiency?",
  "Why does untreated type 1 diabetes lead to ketone production?",
  "List the three classic symptoms of hyperglycaemia.",
  "Why does weight loss occur despite increased hunger in type 1 diabetes?",
  "Name two non-specific symptoms that may accompany early hyperglycaemia.",
  "What does DKA stand for?",
  "List two common clinical features of diabetic ketoacidosis.",
  "What precipitating factor may trigger DKA in a known diabetic?",
  "Why can type 1 diabetes present as a medical emergency?",
  "Name two acute complications of type 1 diabetes.",
  "Name three chronic microvascular complications of diabetes.",
  "Name two chronic macrovascular complications of diabetes.",
  "Why are type 1 diabetics prone to hypoglycaemia?",
  "What is the lifelong treatment required from diagnosis in type 1 diabetes?",
  "What is meant by a basal–bolus insulin regimen?",
  "What monitoring method helps patients adjust insulin dosing?",
  "Why is dietary counselling important in type 1 diabetes?",
  "Name two components of sick-day rules.",
  "Why is regular physical activity recommended for type 1 patients?",
  "Which organs require periodic screening in type 1 diabetes?",
  "Which eye condition is associated with chronic hyperglycaemia?",
  "Which kidney condition is associated with chronic hyperglycaemia?",
  "Which nerve-related condition is associated with chronic diabetes?",
  "Which cardiovascular outcomes are diabetics at higher risk for?",
  "Why is type 1 diabetes considered a chronic disease?",
  "What is meant by 'absolute insulin deficiency'?",
  "What is the exam summary definition of type 1 diabetes?",
  "What is the quick memory hook for type 1 diabetes?"
]
,
  },
  '/DiabetesMellitusType1': {
    category: 'BioChemistry',
    icon: '🔬',
    questions: [
  "What is type 1 diabetes mellitus?",
  "What is the primary defect in type 1 diabetes?",
  "Which pancreatic cells are destroyed in type 1 diabetes?",
  "What hormone becomes severely deficient in type 1 diabetes?",
  "Is type 1 diabetes typically autoimmune or non-autoimmune?",
  "In which age groups does type 1 diabetes most commonly present?",
  "Can type 1 diabetes occur in adults?",
  "What is the typical onset pattern of symptoms in type 1 diabetes?",
  "What genetic system is commonly associated with susceptibility to type 1 diabetes?",
  "Name one possible environmental trigger for type 1 diabetes.",
  "What happens to β-cell mass during disease progression?",
  "Why does hyperglycaemia appear late in the disease process?",
  "What metabolic complication results from absolute insulin deficiency?",
  "Why does untreated type 1 diabetes lead to ketone production?",
  "List the three classic symptoms of hyperglycaemia.",
  "Why does weight loss occur despite increased hunger in type 1 diabetes?",
  "Name two non-specific symptoms that may accompany early hyperglycaemia.",
  "What does DKA stand for?",
  "List two common clinical features of diabetic ketoacidosis.",
  "What precipitating factor may trigger DKA in a known diabetic?",
  "Why can type 1 diabetes present as a medical emergency?",
  "Name two acute complications of type 1 diabetes.",
  "Name three chronic microvascular complications of diabetes.",
  "Name two chronic macrovascular complications of diabetes.",
  "Why are type 1 diabetics prone to hypoglycaemia?",
  "What is the lifelong treatment required from diagnosis in type 1 diabetes?",
  "What is meant by a basal–bolus insulin regimen?",
  "What monitoring method helps patients adjust insulin dosing?",
  "Why is dietary counselling important in type 1 diabetes?",
  "Name two components of sick-day rules.",
  "Why is regular physical activity recommended for type 1 patients?",
  "Which organs require periodic screening in type 1 diabetes?",
  "Which eye condition is associated with chronic hyperglycaemia?",
  "Which kidney condition is associated with chronic hyperglycaemia?",
  "Which nerve-related condition is associated with chronic diabetes?",
  "Which cardiovascular outcomes are diabetics at higher risk for?",
  "Why is type 1 diabetes considered a chronic disease?",
  "What is meant by 'absolute insulin deficiency'?",
  "What is the exam summary definition of type 1 diabetes?",
  "What is the quick memory hook for type 1 diabetes?"
]
,
  },
  '/DiabetesMellitusType1': {
    category: 'BioChemistry',
    icon: '🔬',
    questions: [
  "What is type 1 diabetes mellitus?",
  "What is the primary defect in type 1 diabetes?",
  "Which pancreatic cells are destroyed in type 1 diabetes?",
  "What hormone becomes severely deficient in type 1 diabetes?",
  "Is type 1 diabetes typically autoimmune or non-autoimmune?",
  "In which age groups does type 1 diabetes most commonly present?",
  "Can type 1 diabetes occur in adults?",
  "What is the typical onset pattern of symptoms in type 1 diabetes?",
  "What genetic system is commonly associated with susceptibility to type 1 diabetes?",
  "Name one possible environmental trigger for type 1 diabetes.",
  "What happens to β-cell mass during disease progression?",
  "Why does hyperglycaemia appear late in the disease process?",
  "What metabolic complication results from absolute insulin deficiency?",
  "Why does untreated type 1 diabetes lead to ketone production?",
  "List the three classic symptoms of hyperglycaemia.",
  "Why does weight loss occur despite increased hunger in type 1 diabetes?",
  "Name two non-specific symptoms that may accompany early hyperglycaemia.",
  "What does DKA stand for?",
  "List two common clinical features of diabetic ketoacidosis.",
  "What precipitating factor may trigger DKA in a known diabetic?",
  "Why can type 1 diabetes present as a medical emergency?",
  "Name two acute complications of type 1 diabetes.",
  "Name three chronic microvascular complications of diabetes.",
  "Name two chronic macrovascular complications of diabetes.",
  "Why are type 1 diabetics prone to hypoglycaemia?",
  "What is the lifelong treatment required from diagnosis in type 1 diabetes?",
  "What is meant by a basal–bolus insulin regimen?",
  "What monitoring method helps patients adjust insulin dosing?",
  "Why is dietary counselling important in type 1 diabetes?",
  "Name two components of sick-day rules.",
  "Why is regular physical activity recommended for type 1 patients?",
  "Which organs require periodic screening in type 1 diabetes?",
  "Which eye condition is associated with chronic hyperglycaemia?",
  "Which kidney condition is associated with chronic hyperglycaemia?",
  "Which nerve-related condition is associated with chronic diabetes?",
  "Which cardiovascular outcomes are diabetics at higher risk for?",
  "Why is type 1 diabetes considered a chronic disease?",
  "What is meant by 'absolute insulin deficiency'?",
  "What is the exam summary definition of type 1 diabetes?",
  "What is the quick memory hook for type 1 diabetes?"
]
,
  },
  '/DiabetesMellitusType1': {
    category: 'BioChemistry',
    icon: '🔬',
    questions: [
  "What is type 1 diabetes mellitus?",
  "What is the primary defect in type 1 diabetes?",
  "Which pancreatic cells are destroyed in type 1 diabetes?",
  "What hormone becomes severely deficient in type 1 diabetes?",
  "Is type 1 diabetes typically autoimmune or non-autoimmune?",
  "In which age groups does type 1 diabetes most commonly present?",
  "Can type 1 diabetes occur in adults?",
  "What is the typical onset pattern of symptoms in type 1 diabetes?",
  "What genetic system is commonly associated with susceptibility to type 1 diabetes?",
  "Name one possible environmental trigger for type 1 diabetes.",
  "What happens to β-cell mass during disease progression?",
  "Why does hyperglycaemia appear late in the disease process?",
  "What metabolic complication results from absolute insulin deficiency?",
  "Why does untreated type 1 diabetes lead to ketone production?",
  "List the three classic symptoms of hyperglycaemia.",
  "Why does weight loss occur despite increased hunger in type 1 diabetes?",
  "Name two non-specific symptoms that may accompany early hyperglycaemia.",
  "What does DKA stand for?",
  "List two common clinical features of diabetic ketoacidosis.",
  "What precipitating factor may trigger DKA in a known diabetic?",
  "Why can type 1 diabetes present as a medical emergency?",
  "Name two acute complications of type 1 diabetes.",
  "Name three chronic microvascular complications of diabetes.",
  "Name two chronic macrovascular complications of diabetes.",
  "Why are type 1 diabetics prone to hypoglycaemia?",
  "What is the lifelong treatment required from diagnosis in type 1 diabetes?",
  "What is meant by a basal–bolus insulin regimen?",
  "What monitoring method helps patients adjust insulin dosing?",
  "Why is dietary counselling important in type 1 diabetes?",
  "Name two components of sick-day rules.",
  "Why is regular physical activity recommended for type 1 patients?",
  "Which organs require periodic screening in type 1 diabetes?",
  "Which eye condition is associated with chronic hyperglycaemia?",
  "Which kidney condition is associated with chronic hyperglycaemia?",
  "Which nerve-related condition is associated with chronic diabetes?",
  "Which cardiovascular outcomes are diabetics at higher risk for?",
  "Why is type 1 diabetes considered a chronic disease?",
  "What is meant by 'absolute insulin deficiency'?",
  "What is the exam summary definition of type 1 diabetes?",
  "What is the quick memory hook for type 1 diabetes?"
]
,
  },
  '/DiabetesMellitusType1': {
    category: 'BioChemistry',
    icon: '🔬',
    questions: [
  "What is type 1 diabetes mellitus?",
  "What is the primary defect in type 1 diabetes?",
  "Which pancreatic cells are destroyed in type 1 diabetes?",
  "What hormone becomes severely deficient in type 1 diabetes?",
  "Is type 1 diabetes typically autoimmune or non-autoimmune?",
  "In which age groups does type 1 diabetes most commonly present?",
  "Can type 1 diabetes occur in adults?",
  "What is the typical onset pattern of symptoms in type 1 diabetes?",
  "What genetic system is commonly associated with susceptibility to type 1 diabetes?",
  "Name one possible environmental trigger for type 1 diabetes.",
  "What happens to β-cell mass during disease progression?",
  "Why does hyperglycaemia appear late in the disease process?",
  "What metabolic complication results from absolute insulin deficiency?",
  "Why does untreated type 1 diabetes lead to ketone production?",
  "List the three classic symptoms of hyperglycaemia.",
  "Why does weight loss occur despite increased hunger in type 1 diabetes?",
  "Name two non-specific symptoms that may accompany early hyperglycaemia.",
  "What does DKA stand for?",
  "List two common clinical features of diabetic ketoacidosis.",
  "What precipitating factor may trigger DKA in a known diabetic?",
  "Why can type 1 diabetes present as a medical emergency?",
  "Name two acute complications of type 1 diabetes.",
  "Name three chronic microvascular complications of diabetes.",
  "Name two chronic macrovascular complications of diabetes.",
  "Why are type 1 diabetics prone to hypoglycaemia?",
  "What is the lifelong treatment required from diagnosis in type 1 diabetes?",
  "What is meant by a basal–bolus insulin regimen?",
  "What monitoring method helps patients adjust insulin dosing?",
  "Why is dietary counselling important in type 1 diabetes?",
  "Name two components of sick-day rules.",
  "Why is regular physical activity recommended for type 1 patients?",
  "Which organs require periodic screening in type 1 diabetes?",
  "Which eye condition is associated with chronic hyperglycaemia?",
  "Which kidney condition is associated with chronic hyperglycaemia?",
  "Which nerve-related condition is associated with chronic diabetes?",
  "Which cardiovascular outcomes are diabetics at higher risk for?",
  "Why is type 1 diabetes considered a chronic disease?",
  "What is meant by 'absolute insulin deficiency'?",
  "What is the exam summary definition of type 1 diabetes?",
  "What is the quick memory hook for type 1 diabetes?"
]
,
  },
  '/DiabetesMellitusType1': {
    category: 'BioChemistry',
    icon: '🔬',
    questions: [
  "What is type 1 diabetes mellitus?",
  "What is the primary defect in type 1 diabetes?",
  "Which pancreatic cells are destroyed in type 1 diabetes?",
  "What hormone becomes severely deficient in type 1 diabetes?",
  "Is type 1 diabetes typically autoimmune or non-autoimmune?",
  "In which age groups does type 1 diabetes most commonly present?",
  "Can type 1 diabetes occur in adults?",
  "What is the typical onset pattern of symptoms in type 1 diabetes?",
  "What genetic system is commonly associated with susceptibility to type 1 diabetes?",
  "Name one possible environmental trigger for type 1 diabetes.",
  "What happens to β-cell mass during disease progression?",
  "Why does hyperglycaemia appear late in the disease process?",
  "What metabolic complication results from absolute insulin deficiency?",
  "Why does untreated type 1 diabetes lead to ketone production?",
  "List the three classic symptoms of hyperglycaemia.",
  "Why does weight loss occur despite increased hunger in type 1 diabetes?",
  "Name two non-specific symptoms that may accompany early hyperglycaemia.",
  "What does DKA stand for?",
  "List two common clinical features of diabetic ketoacidosis.",
  "What precipitating factor may trigger DKA in a known diabetic?",
  "Why can type 1 diabetes present as a medical emergency?",
  "Name two acute complications of type 1 diabetes.",
  "Name three chronic microvascular complications of diabetes.",
  "Name two chronic macrovascular complications of diabetes.",
  "Why are type 1 diabetics prone to hypoglycaemia?",
  "What is the lifelong treatment required from diagnosis in type 1 diabetes?",
  "What is meant by a basal–bolus insulin regimen?",
  "What monitoring method helps patients adjust insulin dosing?",
  "Why is dietary counselling important in type 1 diabetes?",
  "Name two components of sick-day rules.",
  "Why is regular physical activity recommended for type 1 patients?",
  "Which organs require periodic screening in type 1 diabetes?",
  "Which eye condition is associated with chronic hyperglycaemia?",
  "Which kidney condition is associated with chronic hyperglycaemia?",
  "Which nerve-related condition is associated with chronic diabetes?",
  "Which cardiovascular outcomes are diabetics at higher risk for?",
  "Why is type 1 diabetes considered a chronic disease?",
  "What is meant by 'absolute insulin deficiency'?",
  "What is the exam summary definition of type 1 diabetes?",
  "What is the quick memory hook for type 1 diabetes?"
]
,
  },
  '/DiabetesMellitusType1': {
    category: 'BioChemistry',
    icon: '🔬',
    questions: [
  "What is type 1 diabetes mellitus?",
  "What is the primary defect in type 1 diabetes?",
  "Which pancreatic cells are destroyed in type 1 diabetes?",
  "What hormone becomes severely deficient in type 1 diabetes?",
  "Is type 1 diabetes typically autoimmune or non-autoimmune?",
  "In which age groups does type 1 diabetes most commonly present?",
  "Can type 1 diabetes occur in adults?",
  "What is the typical onset pattern of symptoms in type 1 diabetes?",
  "What genetic system is commonly associated with susceptibility to type 1 diabetes?",
  "Name one possible environmental trigger for type 1 diabetes.",
  "What happens to β-cell mass during disease progression?",
  "Why does hyperglycaemia appear late in the disease process?",
  "What metabolic complication results from absolute insulin deficiency?",
  "Why does untreated type 1 diabetes lead to ketone production?",
  "List the three classic symptoms of hyperglycaemia.",
  "Why does weight loss occur despite increased hunger in type 1 diabetes?",
  "Name two non-specific symptoms that may accompany early hyperglycaemia.",
  "What does DKA stand for?",
  "List two common clinical features of diabetic ketoacidosis.",
  "What precipitating factor may trigger DKA in a known diabetic?",
  "Why can type 1 diabetes present as a medical emergency?",
  "Name two acute complications of type 1 diabetes.",
  "Name three chronic microvascular complications of diabetes.",
  "Name two chronic macrovascular complications of diabetes.",
  "Why are type 1 diabetics prone to hypoglycaemia?",
  "What is the lifelong treatment required from diagnosis in type 1 diabetes?",
  "What is meant by a basal–bolus insulin regimen?",
  "What monitoring method helps patients adjust insulin dosing?",
  "Why is dietary counselling important in type 1 diabetes?",
  "Name two components of sick-day rules.",
  "Why is regular physical activity recommended for type 1 patients?",
  "Which organs require periodic screening in type 1 diabetes?",
  "Which eye condition is associated with chronic hyperglycaemia?",
  "Which kidney condition is associated with chronic hyperglycaemia?",
  "Which nerve-related condition is associated with chronic diabetes?",
  "Which cardiovascular outcomes are diabetics at higher risk for?",
  "Why is type 1 diabetes considered a chronic disease?",
  "What is meant by 'absolute insulin deficiency'?",
  "What is the exam summary definition of type 1 diabetes?",
  "What is the quick memory hook for type 1 diabetes?"
]
,
  },
  // Add more routes as needed following the same pattern
};
